### PR TITLE
Project finder improvements

### PR DESCRIPTION
**Pull request by david-driscoll**
based on feedback from @Yantrio, made project finding configurable (must be turned on, this will be a breaking change in atom), added logging, and enhanced the way we search, and added some unit tests to cover the basic cases.

cc @nosami

### CODE REVIEW

**Comment by Mpdreamz** [comment]
What if we simply pass the project folder to omnisharp and let omnisharp decide?

I think we discussed starting up without passing a folder immediately in the past I think this would make everything most consistent.

```
start omnisharp
/get-all-projects <folder-path>
/connect-to <folder|scriptcs|sln|project.json|global.json>
```

if `get-all-projects` only returns one candidate we autostart to that (maybe to endpoint could do that returning with `"autostarted": true`. Otherwise we present to available solutions to the editor user.

obviously passing the path straight away would still work for bwc.

THoughts?

**Comment by david-driscoll** [comment]
Do any of these end points exist today?

**Comment by nosami** [comment]
No.

**Comment by nosami** [comment]
@Mpdreamz your question belongs over on omnisharp-roslyn

**Comment by david-driscoll** [comment]
:ship: set sail!

**Pull request merged**
